version: '3'

services:
  expo-app:
    build: .
    container_name: expo-dev-container
    volumes:
      - ./:/app
    network_mode: "host"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    restart: unless-stopped
